services:
        backend:
                image: echoesofthefuture/echoes-of-the-future-server
                command: sh -c "npm run build && npm run prod"
                expose:
                        - 5000
                environment:
                        - NODE_ENV=production
                        - SERVER_PORT=5000
                depends_on:
                        - postgres

        frontend:
                image: echoesofthefuture/echoes-of-the-future-client
                command: sh -c "npm run build"
                volumes:
                        - web-client-build:/app/build
                environment:
                        - NODE_ENV=production
        postgres:
                image: postgres
                restart: always
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_PASSWORD: example

        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080

        nginx:
                image: nginx:1.21.3
                depends_on:
                        - backend
                        - frontend
                restart: always
                ports:
                        - ${GATEWAY_PORT}:80
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - web-client-build:/web-client-build
                        - ./logs:/var/log/nginx
volumes:
        web-client-build:
