import { TChallenge } from "./Challenge";

export const challenges: TChallenge[] = [
  {
    id: 1,
    name: "Challenge User 4 - 4H",
    actions: [
      {
        id: 1,
        name: "Arrêtons de niquer nos mers et défendons nos grands pères",
        description: "Arrêtons de niquer nos mers",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
    ],
    startAt: "2018-07-22T15:00:0",
    endAt: "2018-07-22T19:00:0",
    creator: 4,
  },
  {
    id: 2,
    name: "Challenge Creator - 1J",
    actions: [
      {
        id: 1,
        name: "string",
        description: "string",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
      {
        id: 3,
        name: "string",
        description: "string",
        points: 15,
        need_proof: true,
      },
    ],
    startAt: "2018-09-22T15:00:0",
    endAt: "2018-09-23T15:00:0",
    creator: 1,
  },
  {
    id: 3,
    name: "Challenge User 2 - 30M",
    actions: [
      {
        id: 1,
        name: "string",
        description: "string",
        points: 2,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
      {
        id: 3,
        name: "string",
        description: "string",
        points: 20,
        need_proof: false,
      },
      {
        id: 4,
        name: "string",
        description: "string",
        points: 12,
        need_proof: false,
      },
    ],
    startAt: "2018-09-22T15:00:0",
    endAt: "2018-09-22T15:30:0",
    creator: 2,
  },
  {
    id: 4,
    name: "Challenge Creator - 1min",
    actions: [
      {
        id: 1,
        name: "Arrêtons de niquer nos mers et défendons nos grands pères",
        description: "Arrêtons de niquer nos mers",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
    ],
    startAt: "2018-07-22T15:00:0",
    endAt: "2018-07-22T15:01:0",
    creator: 1,
  },
  {
    id: 4,
    name: "Challenge User2 - 1min",
    actions: [
      {
        id: 1,
        name: "Arrêtons de niquer nos mers et défendons nos grands pères",
        description: "Arrêtons de niquer nos mers",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
    ],
    startAt: "2018-07-22T15:00:0",
    endAt: "2018-07-22T15:01:0",
    creator: 2,
  },
  {
    id: 5,
    name: "Challenge Done",
    actions: [
      {
        id: 1,
        name: "Arrêtons de niquer nos mers et défendons nos grands pères",
        description: "Arrêtons de niquer nos mers",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
    ],
    startAt: "2018-07-22T15:00:0",
    endAt: "2018-07-22T00:01:0",
    creator: 2,
  },
  {
    id: 5,
    name: "Challenge Creator Done",
    actions: [
      {
        id: 1,
        name: "Arrêtons de niquer nos mers et défendons nos grands pères",
        description: "Arrêtons de niquer nos mers",
        points: 10,
        need_proof: false,
      },
      {
        id: 2,
        name: "string",
        description: "string",
        points: 5,
        need_proof: false,
      },
    ],
    startAt: "2018-07-22T15:00:0",
    endAt: "2018-07-22T00:01:0",
    creator: 1,
  },
];
